// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirPollutionService.proto
// Protobuf Java Version: 4.26.1

package com.chuntao.service;

public final class AirPollutionService {
  private AirPollutionService() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      AirPollutionService.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chuntao_SensorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chuntao_SensorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chuntao_SensorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chuntao_SensorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chuntao_VentilationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chuntao_VentilationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chuntao_NotificationMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chuntao_NotificationMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031AirPollutionService.proto\022\013com.chuntao" +
      "\"\"\n\rSensorRequest\022\021\n\tsensor_id\030\001 \001(\005\"\232\001\n" +
      "\016SensorResponse\022\020\n\010location\030\001 \001(\t\022\n\n\002PM\030" +
      "\002 \001(\002\022\023\n\013temperature\030\003 \001(\002\022\013\n\003VOC\030\004 \001(\002\022" +
      "\020\n\010humidity\030\005 \001(\002\022\n\n\002CO\030\006 \001(\002\022\027\n\017polluti" +
      "on_level\030\007 \001(\005\022\021\n\ttimestamp\030\010 \001(\003\"c\n\023Ven" +
      "tilationResponse\022\020\n\010location\030\001 \001(\t\022\026\n\016po" +
      "llution_item\030\002 \001(\t\022\017\n\007turn_on\030\003 \001(\010\022\021\n\tt" +
      "imestamp\030\004 \001(\003\"R\n\023NotificationMessage\022\020\n" +
      "\010location\030\001 \001(\t\022\023\n\013air_quality\030\002 \001(\t\022\024\n\014" +
      "vent_control\030\003 \001(\t2\253\001\n\006Sensor\022M\n\020GetAllS" +
      "ensorData\022\032.com.chuntao.SensorRequest\032\033." +
      "com.chuntao.SensorResponse\"\000\022R\n\023GetSingl" +
      "eSensorData\022\032.com.chuntao.SensorRequest\032" +
      "\033.com.chuntao.SensorResponse\"\0000\0012h\n\013Vent" +
      "ilation\022Y\n\022VentilationControl\022\033.com.chun" +
      "tao.SensorResponse\032 .com.chuntao.Ventila" +
      "tionResponse\"\000(\0010\0012n\n\014Notification\022^\n\024Re" +
      "ceiveNotifications\022 .com.chuntao.Ventila" +
      "tionResponse\032 .com.chuntao.NotificationM" +
      "essage\"\000(\001B,\n\023com.chuntao.serviceB\023AirPo" +
      "llutionServiceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_chuntao_SensorRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chuntao_SensorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chuntao_SensorRequest_descriptor,
        new java.lang.String[] { "SensorId", });
    internal_static_com_chuntao_SensorResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_chuntao_SensorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chuntao_SensorResponse_descriptor,
        new java.lang.String[] { "Location", "PM", "Temperature", "VOC", "Humidity", "CO", "PollutionLevel", "Timestamp", });
    internal_static_com_chuntao_VentilationResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_chuntao_VentilationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chuntao_VentilationResponse_descriptor,
        new java.lang.String[] { "Location", "PollutionItem", "TurnOn", "Timestamp", });
    internal_static_com_chuntao_NotificationMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_chuntao_NotificationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chuntao_NotificationMessage_descriptor,
        new java.lang.String[] { "Location", "AirQuality", "VentControl", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
