// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Notification.proto

// Protobuf Java Version: 4.26.1
package com.chuntao.service;

public interface HVACMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chuntao.service.HVACMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   * @return The status.
   */
  boolean getStatus();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.google.protobuf.Timestamp updated_time = 3;</code>
   * @return Whether the updatedTime field is set.
   */
  boolean hasUpdatedTime();
  /**
   * <code>.google.protobuf.Timestamp updated_time = 3;</code>
   * @return The updatedTime.
   */
  com.google.protobuf.Timestamp getUpdatedTime();
  /**
   * <code>.google.protobuf.Timestamp updated_time = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedTimeOrBuilder();
}
