// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HVAC.proto

// Protobuf Java Version: 4.26.1
package com.chuntao.service;

public interface HVACRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chuntao.HVACRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 pollution_level = 1;</code>
   * @return The pollutionLevel.
   */
  int getPollutionLevel();
}
