// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HVAC.proto

// Protobuf Java Version: 4.26.1
package com.chuntao.service;

public interface HVACCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chuntao.HVACCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.chuntao.HVACCommand.Action action = 1;</code>
   * @return The enum numeric value on the wire for action.
   */
  int getActionValue();
  /**
   * <code>.com.chuntao.HVACCommand.Action action = 1;</code>
   * @return The action.
   */
  com.chuntao.service.HVACCommand.Action getAction();
}
