// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HVAC.proto
// Protobuf Java Version: 4.26.1

package com.chuntao.service;

public final class HVACService {
  private HVACService() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      HVACService.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chuntao_HVACRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chuntao_HVACRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chuntao_HVACCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chuntao_HVACCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chuntao_HVACResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chuntao_HVACResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nHVAC.proto\022\013com.chuntao\032\037google/protob" +
      "uf/timestamp.proto\032\014Sensor.proto\"&\n\013HVAC" +
      "Request\022\027\n\017pollution_level\030\001 \001(\005\"]\n\013HVAC" +
      "Command\022/\n\006action\030\001 \001(\0162\037.com.chuntao.HV" +
      "ACCommand.Action\"\035\n\006Action\022\t\n\005START\020\000\022\010\n" +
      "\004STOP\020\001\"f\n\014HVACResponse\022\016\n\006status\030\001 \001(\t\022" +
      "\027\n\017pollution_level\030\002 \001(\005\022-\n\ttimestamp\030\003 " +
      "\001(\0132\032.google.protobuf.Timestamp2\226\001\n\004HVAC" +
      "\022E\n\013HVACControl\022\030.com.chuntao.HVACReques" +
      "t\032\030.com.chuntao.HVACCommand\"\000(\001\022G\n\nHVACS" +
      "witch\022\030.com.chuntao.HVACCommand\032\031.com.ch" +
      "untao.HVACResponse\"\000(\0010\001B$\n\023com.chuntao." +
      "serviceB\013HVACServiceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.chuntao.service.SensorService.getDescriptor(),
        });
    internal_static_com_chuntao_HVACRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chuntao_HVACRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chuntao_HVACRequest_descriptor,
        new java.lang.String[] { "PollutionLevel", });
    internal_static_com_chuntao_HVACCommand_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_chuntao_HVACCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chuntao_HVACCommand_descriptor,
        new java.lang.String[] { "Action", });
    internal_static_com_chuntao_HVACResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_chuntao_HVACResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chuntao_HVACResponse_descriptor,
        new java.lang.String[] { "Status", "PollutionLevel", "Timestamp", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.chuntao.service.SensorService.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
