// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HVAC.proto

// Protobuf Java Version: 4.26.1
package com.chuntao.service;

public interface HVACResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chuntao.HVACResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 pollution_level = 2;</code>
   * @return The pollutionLevel.
   */
  int getPollutionLevel();

  /**
   * <code>.google.protobuf.Timestamp updated_time = 4;</code>
   * @return Whether the updatedTime field is set.
   */
  boolean hasUpdatedTime();
  /**
   * <code>.google.protobuf.Timestamp updated_time = 4;</code>
   * @return The updatedTime.
   */
  com.google.protobuf.Timestamp getUpdatedTime();
  /**
   * <code>.google.protobuf.Timestamp updated_time = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedTimeOrBuilder();
}
