// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HVAC.proto

// Protobuf Java Version: 4.26.1
package com.chuntao.service;

/**
 * Protobuf type {@code com.chuntao.HVACRequest}
 */
public final class HVACRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.chuntao.HVACRequest)
    HVACRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      HVACRequest.class.getName());
  }
  // Use HVACRequest.newBuilder() to construct.
  private HVACRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private HVACRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.chuntao.service.HVACService.internal_static_com_chuntao_HVACRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.chuntao.service.HVACService.internal_static_com_chuntao_HVACRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.chuntao.service.HVACRequest.class, com.chuntao.service.HVACRequest.Builder.class);
  }

  public static final int POLLUTION_LEVEL_FIELD_NUMBER = 1;
  private int pollutionLevel_ = 0;
  /**
   * <code>int32 pollution_level = 1;</code>
   * @return The pollutionLevel.
   */
  @java.lang.Override
  public int getPollutionLevel() {
    return pollutionLevel_;
  }

  public static final int TEMPERATURE_FIELD_NUMBER = 2;
  private float temperature_ = 0F;
  /**
   * <code>float temperature = 2;</code>
   * @return The temperature.
   */
  @java.lang.Override
  public float getTemperature() {
    return temperature_;
  }

  public static final int HUMIDITY_FIELD_NUMBER = 3;
  private float humidity_ = 0F;
  /**
   * <code>float humidity = 3;</code>
   * @return The humidity.
   */
  @java.lang.Override
  public float getHumidity() {
    return humidity_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (pollutionLevel_ != 0) {
      output.writeInt32(1, pollutionLevel_);
    }
    if (java.lang.Float.floatToRawIntBits(temperature_) != 0) {
      output.writeFloat(2, temperature_);
    }
    if (java.lang.Float.floatToRawIntBits(humidity_) != 0) {
      output.writeFloat(3, humidity_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (pollutionLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, pollutionLevel_);
    }
    if (java.lang.Float.floatToRawIntBits(temperature_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, temperature_);
    }
    if (java.lang.Float.floatToRawIntBits(humidity_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, humidity_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.chuntao.service.HVACRequest)) {
      return super.equals(obj);
    }
    com.chuntao.service.HVACRequest other = (com.chuntao.service.HVACRequest) obj;

    if (getPollutionLevel()
        != other.getPollutionLevel()) return false;
    if (java.lang.Float.floatToIntBits(getTemperature())
        != java.lang.Float.floatToIntBits(
            other.getTemperature())) return false;
    if (java.lang.Float.floatToIntBits(getHumidity())
        != java.lang.Float.floatToIntBits(
            other.getHumidity())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + POLLUTION_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getPollutionLevel();
    hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getTemperature());
    hash = (37 * hash) + HUMIDITY_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getHumidity());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.chuntao.service.HVACRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.chuntao.service.HVACRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.chuntao.service.HVACRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.chuntao.service.HVACRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.chuntao.service.HVACRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.chuntao.service.HVACRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.chuntao.service.HVACRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.chuntao.service.HVACRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.chuntao.service.HVACRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.chuntao.service.HVACRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.chuntao.service.HVACRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.chuntao.service.HVACRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.chuntao.service.HVACRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.chuntao.HVACRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.chuntao.HVACRequest)
      com.chuntao.service.HVACRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chuntao.service.HVACService.internal_static_com_chuntao_HVACRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chuntao.service.HVACService.internal_static_com_chuntao_HVACRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chuntao.service.HVACRequest.class, com.chuntao.service.HVACRequest.Builder.class);
    }

    // Construct using com.chuntao.service.HVACRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      pollutionLevel_ = 0;
      temperature_ = 0F;
      humidity_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.chuntao.service.HVACService.internal_static_com_chuntao_HVACRequest_descriptor;
    }

    @java.lang.Override
    public com.chuntao.service.HVACRequest getDefaultInstanceForType() {
      return com.chuntao.service.HVACRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.chuntao.service.HVACRequest build() {
      com.chuntao.service.HVACRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.chuntao.service.HVACRequest buildPartial() {
      com.chuntao.service.HVACRequest result = new com.chuntao.service.HVACRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.chuntao.service.HVACRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.pollutionLevel_ = pollutionLevel_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.temperature_ = temperature_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.humidity_ = humidity_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.chuntao.service.HVACRequest) {
        return mergeFrom((com.chuntao.service.HVACRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.chuntao.service.HVACRequest other) {
      if (other == com.chuntao.service.HVACRequest.getDefaultInstance()) return this;
      if (other.getPollutionLevel() != 0) {
        setPollutionLevel(other.getPollutionLevel());
      }
      if (other.getTemperature() != 0F) {
        setTemperature(other.getTemperature());
      }
      if (other.getHumidity() != 0F) {
        setHumidity(other.getHumidity());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              pollutionLevel_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 21: {
              temperature_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            case 29: {
              humidity_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int pollutionLevel_ ;
    /**
     * <code>int32 pollution_level = 1;</code>
     * @return The pollutionLevel.
     */
    @java.lang.Override
    public int getPollutionLevel() {
      return pollutionLevel_;
    }
    /**
     * <code>int32 pollution_level = 1;</code>
     * @param value The pollutionLevel to set.
     * @return This builder for chaining.
     */
    public Builder setPollutionLevel(int value) {

      pollutionLevel_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 pollution_level = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPollutionLevel() {
      bitField0_ = (bitField0_ & ~0x00000001);
      pollutionLevel_ = 0;
      onChanged();
      return this;
    }

    private float temperature_ ;
    /**
     * <code>float temperature = 2;</code>
     * @return The temperature.
     */
    @java.lang.Override
    public float getTemperature() {
      return temperature_;
    }
    /**
     * <code>float temperature = 2;</code>
     * @param value The temperature to set.
     * @return This builder for chaining.
     */
    public Builder setTemperature(float value) {

      temperature_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>float temperature = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTemperature() {
      bitField0_ = (bitField0_ & ~0x00000002);
      temperature_ = 0F;
      onChanged();
      return this;
    }

    private float humidity_ ;
    /**
     * <code>float humidity = 3;</code>
     * @return The humidity.
     */
    @java.lang.Override
    public float getHumidity() {
      return humidity_;
    }
    /**
     * <code>float humidity = 3;</code>
     * @param value The humidity to set.
     * @return This builder for chaining.
     */
    public Builder setHumidity(float value) {

      humidity_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>float humidity = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHumidity() {
      bitField0_ = (bitField0_ & ~0x00000004);
      humidity_ = 0F;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.chuntao.HVACRequest)
  }

  // @@protoc_insertion_point(class_scope:com.chuntao.HVACRequest)
  private static final com.chuntao.service.HVACRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.chuntao.service.HVACRequest();
  }

  public static com.chuntao.service.HVACRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HVACRequest>
      PARSER = new com.google.protobuf.AbstractParser<HVACRequest>() {
    @java.lang.Override
    public HVACRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HVACRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HVACRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.chuntao.service.HVACRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

