// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hvac.proto
// Protobuf Java Version: 4.26.1

package com.chuntao.service;

public final class HvacService {
  private HvacService() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      HvacService.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chuntao_HvacRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chuntao_HvacRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chuntao_HvacCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chuntao_HvacCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chuntao_HvacResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chuntao_HvacResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nhvac.proto\022\013com.chuntao\032\037google/protob" +
      "uf/timestamp.proto\032\014sensor.proto\"&\n\013Hvac" +
      "Request\022\027\n\017pollution_level\030\001 \001(\005\"\217\001\n\013Hva" +
      "cCommand\022/\n\006action\030\001 \001(\0162\037.com.chuntao.H" +
      "vacCommand.Action\0220\n\014updated_time\030\002 \001(\0132" +
      "\032.google.protobuf.Timestamp\"\035\n\006Action\022\t\n" +
      "\005START\020\000\022\010\n\004STOP\020\001\"i\n\014HvacResponse\022\016\n\006st" +
      "atus\030\001 \001(\t\022\027\n\017pollution_level\030\002 \001(\005\0220\n\014u" +
      "pdated_time\030\003 \001(\0132\032.google.protobuf.Time" +
      "stamp2\226\001\n\004HVAC\022E\n\013HvacControl\022\030.com.chun" +
      "tao.HvacRequest\032\030.com.chuntao.HvacComman" +
      "d\"\000(\001\022G\n\nHvacSwitch\022\030.com.chuntao.HvacCo" +
      "mmand\032\031.com.chuntao.HvacResponse\"\000(\0010\001B$" +
      "\n\023com.chuntao.serviceB\013HvacServiceP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.chuntao.service.SensorService.getDescriptor(),
        });
    internal_static_com_chuntao_HvacRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chuntao_HvacRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chuntao_HvacRequest_descriptor,
        new java.lang.String[] { "PollutionLevel", });
    internal_static_com_chuntao_HvacCommand_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_chuntao_HvacCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chuntao_HvacCommand_descriptor,
        new java.lang.String[] { "Action", "UpdatedTime", });
    internal_static_com_chuntao_HvacResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_chuntao_HvacResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chuntao_HvacResponse_descriptor,
        new java.lang.String[] { "Status", "PollutionLevel", "UpdatedTime", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.chuntao.service.SensorService.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
