// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hvac.proto

// Protobuf Java Version: 4.26.1
package com.chuntao.service;

/**
 * Protobuf type {@code com.chuntao.HvacCommand}
 */
public final class HvacCommand extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.chuntao.HvacCommand)
    HvacCommandOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      HvacCommand.class.getName());
  }
  // Use HvacCommand.newBuilder() to construct.
  private HvacCommand(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private HvacCommand() {
    action_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.chuntao.service.HvacService.internal_static_com_chuntao_HvacCommand_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.chuntao.service.HvacService.internal_static_com_chuntao_HvacCommand_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.chuntao.service.HvacCommand.class, com.chuntao.service.HvacCommand.Builder.class);
  }

  /**
   * Protobuf enum {@code com.chuntao.HvacCommand.Action}
   */
  public enum Action
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>START = 0;</code>
     */
    START(0),
    /**
     * <code>STOP = 1;</code>
     */
    STOP(1),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        Action.class.getName());
    }
    /**
     * <code>START = 0;</code>
     */
    public static final int START_VALUE = 0;
    /**
     * <code>STOP = 1;</code>
     */
    public static final int STOP_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Action valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Action forNumber(int value) {
      switch (value) {
        case 0: return START;
        case 1: return STOP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Action>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Action> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Action>() {
            public Action findValueByNumber(int number) {
              return Action.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.chuntao.service.HvacCommand.getDescriptor().getEnumTypes().get(0);
    }

    private static final Action[] VALUES = values();

    public static Action valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Action(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.chuntao.HvacCommand.Action)
  }

  private int bitField0_;
  public static final int ACTION_FIELD_NUMBER = 1;
  private int action_ = 0;
  /**
   * <code>.com.chuntao.HvacCommand.Action action = 1;</code>
   * @return The enum numeric value on the wire for action.
   */
  @java.lang.Override public int getActionValue() {
    return action_;
  }
  /**
   * <code>.com.chuntao.HvacCommand.Action action = 1;</code>
   * @return The action.
   */
  @java.lang.Override public com.chuntao.service.HvacCommand.Action getAction() {
    com.chuntao.service.HvacCommand.Action result = com.chuntao.service.HvacCommand.Action.forNumber(action_);
    return result == null ? com.chuntao.service.HvacCommand.Action.UNRECOGNIZED : result;
  }

  public static final int UPDATED_TIME_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp updatedTime_;
  /**
   * <code>.google.protobuf.Timestamp updated_time = 2;</code>
   * @return Whether the updatedTime field is set.
   */
  @java.lang.Override
  public boolean hasUpdatedTime() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp updated_time = 2;</code>
   * @return The updatedTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getUpdatedTime() {
    return updatedTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp updated_time = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getUpdatedTimeOrBuilder() {
    return updatedTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (action_ != com.chuntao.service.HvacCommand.Action.START.getNumber()) {
      output.writeEnum(1, action_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getUpdatedTime());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (action_ != com.chuntao.service.HvacCommand.Action.START.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, action_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUpdatedTime());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.chuntao.service.HvacCommand)) {
      return super.equals(obj);
    }
    com.chuntao.service.HvacCommand other = (com.chuntao.service.HvacCommand) obj;

    if (action_ != other.action_) return false;
    if (hasUpdatedTime() != other.hasUpdatedTime()) return false;
    if (hasUpdatedTime()) {
      if (!getUpdatedTime()
          .equals(other.getUpdatedTime())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + action_;
    if (hasUpdatedTime()) {
      hash = (37 * hash) + UPDATED_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getUpdatedTime().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.chuntao.service.HvacCommand parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.chuntao.service.HvacCommand parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.chuntao.service.HvacCommand parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.chuntao.service.HvacCommand parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.chuntao.service.HvacCommand parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.chuntao.service.HvacCommand parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.chuntao.service.HvacCommand parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.chuntao.service.HvacCommand parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.chuntao.service.HvacCommand parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.chuntao.service.HvacCommand parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.chuntao.service.HvacCommand parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.chuntao.service.HvacCommand parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.chuntao.service.HvacCommand prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.chuntao.HvacCommand}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.chuntao.HvacCommand)
      com.chuntao.service.HvacCommandOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chuntao.service.HvacService.internal_static_com_chuntao_HvacCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chuntao.service.HvacService.internal_static_com_chuntao_HvacCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chuntao.service.HvacCommand.class, com.chuntao.service.HvacCommand.Builder.class);
    }

    // Construct using com.chuntao.service.HvacCommand.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getUpdatedTimeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      action_ = 0;
      updatedTime_ = null;
      if (updatedTimeBuilder_ != null) {
        updatedTimeBuilder_.dispose();
        updatedTimeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.chuntao.service.HvacService.internal_static_com_chuntao_HvacCommand_descriptor;
    }

    @java.lang.Override
    public com.chuntao.service.HvacCommand getDefaultInstanceForType() {
      return com.chuntao.service.HvacCommand.getDefaultInstance();
    }

    @java.lang.Override
    public com.chuntao.service.HvacCommand build() {
      com.chuntao.service.HvacCommand result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.chuntao.service.HvacCommand buildPartial() {
      com.chuntao.service.HvacCommand result = new com.chuntao.service.HvacCommand(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.chuntao.service.HvacCommand result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.action_ = action_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.updatedTime_ = updatedTimeBuilder_ == null
            ? updatedTime_
            : updatedTimeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.chuntao.service.HvacCommand) {
        return mergeFrom((com.chuntao.service.HvacCommand)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.chuntao.service.HvacCommand other) {
      if (other == com.chuntao.service.HvacCommand.getDefaultInstance()) return this;
      if (other.action_ != 0) {
        setActionValue(other.getActionValue());
      }
      if (other.hasUpdatedTime()) {
        mergeUpdatedTime(other.getUpdatedTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              action_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getUpdatedTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int action_ = 0;
    /**
     * <code>.com.chuntao.HvacCommand.Action action = 1;</code>
     * @return The enum numeric value on the wire for action.
     */
    @java.lang.Override public int getActionValue() {
      return action_;
    }
    /**
     * <code>.com.chuntao.HvacCommand.Action action = 1;</code>
     * @param value The enum numeric value on the wire for action to set.
     * @return This builder for chaining.
     */
    public Builder setActionValue(int value) {
      action_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.chuntao.HvacCommand.Action action = 1;</code>
     * @return The action.
     */
    @java.lang.Override
    public com.chuntao.service.HvacCommand.Action getAction() {
      com.chuntao.service.HvacCommand.Action result = com.chuntao.service.HvacCommand.Action.forNumber(action_);
      return result == null ? com.chuntao.service.HvacCommand.Action.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.chuntao.HvacCommand.Action action = 1;</code>
     * @param value The action to set.
     * @return This builder for chaining.
     */
    public Builder setAction(com.chuntao.service.HvacCommand.Action value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      action_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.chuntao.HvacCommand.Action action = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAction() {
      bitField0_ = (bitField0_ & ~0x00000001);
      action_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp updatedTime_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updatedTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp updated_time = 2;</code>
     * @return Whether the updatedTime field is set.
     */
    public boolean hasUpdatedTime() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp updated_time = 2;</code>
     * @return The updatedTime.
     */
    public com.google.protobuf.Timestamp getUpdatedTime() {
      if (updatedTimeBuilder_ == null) {
        return updatedTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedTime_;
      } else {
        return updatedTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp updated_time = 2;</code>
     */
    public Builder setUpdatedTime(com.google.protobuf.Timestamp value) {
      if (updatedTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updatedTime_ = value;
      } else {
        updatedTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_time = 2;</code>
     */
    public Builder setUpdatedTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (updatedTimeBuilder_ == null) {
        updatedTime_ = builderForValue.build();
      } else {
        updatedTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_time = 2;</code>
     */
    public Builder mergeUpdatedTime(com.google.protobuf.Timestamp value) {
      if (updatedTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          updatedTime_ != null &&
          updatedTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getUpdatedTimeBuilder().mergeFrom(value);
        } else {
          updatedTime_ = value;
        }
      } else {
        updatedTimeBuilder_.mergeFrom(value);
      }
      if (updatedTime_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_time = 2;</code>
     */
    public Builder clearUpdatedTime() {
      bitField0_ = (bitField0_ & ~0x00000002);
      updatedTime_ = null;
      if (updatedTimeBuilder_ != null) {
        updatedTimeBuilder_.dispose();
        updatedTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_time = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getUpdatedTimeBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getUpdatedTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp updated_time = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getUpdatedTimeOrBuilder() {
      if (updatedTimeBuilder_ != null) {
        return updatedTimeBuilder_.getMessageOrBuilder();
      } else {
        return updatedTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : updatedTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp updated_time = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getUpdatedTimeFieldBuilder() {
      if (updatedTimeBuilder_ == null) {
        updatedTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getUpdatedTime(),
                getParentForChildren(),
                isClean());
        updatedTime_ = null;
      }
      return updatedTimeBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:com.chuntao.HvacCommand)
  }

  // @@protoc_insertion_point(class_scope:com.chuntao.HvacCommand)
  private static final com.chuntao.service.HvacCommand DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.chuntao.service.HvacCommand();
  }

  public static com.chuntao.service.HvacCommand getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HvacCommand>
      PARSER = new com.google.protobuf.AbstractParser<HvacCommand>() {
    @java.lang.Override
    public HvacCommand parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HvacCommand> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HvacCommand> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.chuntao.service.HvacCommand getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

