// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hvac.proto

// Protobuf Java Version: 4.26.1
package com.chuntao.service;

public interface HvacCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chuntao.HvacCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.chuntao.HvacCommand.Action action = 1;</code>
   * @return The enum numeric value on the wire for action.
   */
  int getActionValue();
  /**
   * <code>.com.chuntao.HvacCommand.Action action = 1;</code>
   * @return The action.
   */
  com.chuntao.service.HvacCommand.Action getAction();

  /**
   * <code>.google.protobuf.Timestamp updated_time = 2;</code>
   * @return Whether the updatedTime field is set.
   */
  boolean hasUpdatedTime();
  /**
   * <code>.google.protobuf.Timestamp updated_time = 2;</code>
   * @return The updatedTime.
   */
  com.google.protobuf.Timestamp getUpdatedTime();
  /**
   * <code>.google.protobuf.Timestamp updated_time = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedTimeOrBuilder();
}
