// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Notification.proto
// Protobuf Java Version: 4.26.1

package com.chuntao.service;

public final class NotificationService {
  private NotificationService() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      NotificationService.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chuntao_NotificationMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chuntao_NotificationMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022Notification.proto\022\013com.chuntao\032\037googl" +
      "e/protobuf/timestamp.proto\032\014Sensor.proto" +
      "\032\nHVAC.proto\"|\n\023NotificationMessage\022\020\n\010l" +
      "ocation\030\001 \001(\t\022\023\n\013air_quality\030\002 \001(\t\022\017\n\007me" +
      "ssage\030\003 \001(\t\022-\n\ttimestamp\030\004 \001(\0132\032.google." +
      "protobuf.Timestamp2\276\001\n\014Notification\022X\n\023S" +
      "ensorNotifications\022\033.com.chuntao.SensorR" +
      "esponse\032 .com.chuntao.NotificationMessag" +
      "e\"\0000\001\022T\n\021VentNotifications\022\031.com.chuntao" +
      ".HVACResponse\032 .com.chuntao.Notification" +
      "Message\"\0000\001B,\n\023com.chuntao.serviceB\023Noti" +
      "ficationServiceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.chuntao.service.SensorService.getDescriptor(),
          com.chuntao.service.HVACService.getDescriptor(),
        });
    internal_static_com_chuntao_NotificationMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chuntao_NotificationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chuntao_NotificationMessage_descriptor,
        new java.lang.String[] { "Location", "AirQuality", "Message", "Timestamp", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.chuntao.service.SensorService.getDescriptor();
    com.chuntao.service.HVACService.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
