// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Notification.proto
// Protobuf Java Version: 4.26.1

package com.chuntao.service;

public final class NotificationService {
  private NotificationService() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      NotificationService.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chuntao_service_NotificationMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chuntao_service_NotificationMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022Notification.proto\022\023com.chuntao.servic" +
      "e\032\037google/protobuf/timestamp.proto\032\014Sens" +
      "or.proto\032\nHVAC.proto\"|\n\023NotificationMess" +
      "age\022\020\n\010location\030\001 \001(\t\022\023\n\013air_quality\030\002 \001" +
      "(\t\022\017\n\007message\030\003 \001(\t\022-\n\ttimestamp\030\004 \001(\0132\032" +
      ".google.protobuf.Timestamp2\317\001\n\014Notificat" +
      "ion\022a\n\023SensorNotifications\022\034.com.chuntao" +
      ".AnalyseResponse\032(.com.chuntao.service.N" +
      "otificationMessage\"\0000\001\022\\\n\021HVACNotificati" +
      "ons\022\031.com.chuntao.HVACResponse\032(.com.chu" +
      "ntao.service.NotificationMessage\"\0000\001B,\n\023" +
      "com.chuntao.serviceB\023NotificationService" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.chuntao.service.SensorService.getDescriptor(),
          com.chuntao.service.HVACService.getDescriptor(),
        });
    internal_static_com_chuntao_service_NotificationMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chuntao_service_NotificationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chuntao_service_NotificationMessage_descriptor,
        new java.lang.String[] { "Location", "AirQuality", "Message", "Timestamp", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.chuntao.service.SensorService.getDescriptor();
    com.chuntao.service.HVACService.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
