// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Notification.proto

// Protobuf Java Version: 4.26.1
package com.chuntao.service;

public interface NotificationMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chuntao.NotificationMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   * @return The location.
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string air_quality = 2;</code>
   * @return The airQuality.
   */
  java.lang.String getAirQuality();
  /**
   * <code>string air_quality = 2;</code>
   * @return The bytes for airQuality.
   */
  com.google.protobuf.ByteString
      getAirQualityBytes();

  /**
   * <code>string HVAC_control = 3;</code>
   * @return The hVACControl.
   */
  java.lang.String getHVACControl();
  /**
   * <code>string HVAC_control = 3;</code>
   * @return The bytes for hVACControl.
   */
  com.google.protobuf.ByteString
      getHVACControlBytes();

  /**
   * <code>string message = 4;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 4;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
