// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sensor.proto

// Protobuf Java Version: 4.26.1
package com.chuntao.service;

public interface PollutionLevelResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chuntao.PollutionLevelResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 pollution_level = 1;</code>
   * @return The pollutionLevel.
   */
  int getPollutionLevel();
}
