// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensor.proto

// Protobuf Java Version: 4.26.1
package com.chuntao.service;

public interface SensorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chuntao.SensorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sensor_id = 1;</code>
   * @return The sensorId.
   */
  int getSensorId();
}
