// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartAirPollution.proto

// Protobuf Java Version: 4.26.1
package com.chuntao.service;

public interface SensorMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chuntao.SensorMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   * @return The location.
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string air_quality = 2;</code>
   * @return The airQuality.
   */
  java.lang.String getAirQuality();
  /**
   * <code>string air_quality = 2;</code>
   * @return The bytes for airQuality.
   */
  com.google.protobuf.ByteString
      getAirQualityBytes();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();
}
