// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sensor.proto

// Protobuf Java Version: 4.26.1
package com.chuntao.service;

public interface SensorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chuntao.SensorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   * @return The location.
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
