// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartAirPollution.proto
// Protobuf Java Version: 4.26.1

package com.chuntao.service;

public final class SensorService {
  private SensorService() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      SensorService.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chuntao_SensorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chuntao_SensorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chuntao_SensorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chuntao_SensorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chuntao_AnalyseResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chuntao_AnalyseResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chuntao_HVACCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chuntao_HVACCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chuntao_HVACResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chuntao_HVACResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chuntao_SensorMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chuntao_SensorMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chuntao_HVACMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chuntao_HVACMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027SmartAirPollution.proto\022\013com.chuntao\032\037" +
      "google/protobuf/timestamp.proto\"\"\n\rSenso" +
      "rRequest\022\021\n\tsensor_id\030\001 \001(\005\"p\n\016SensorRes" +
      "ponse\022\020\n\010location\030\001 \001(\t\022\014\n\004PM25\030\002 \001(\002\022\023\n" +
      "\013temperature\030\003 \001(\002\022\013\n\003VOC\030\004 \001(\002\022\020\n\010humid" +
      "ity\030\005 \001(\002\022\n\n\002CO\030\006 \001(\002\"\215\001\n\017AnalyseRespons" +
      "e\022\017\n\007analyse\030\001 \001(\t\022\020\n\010location\030\002 \001(\t\022\027\n\017" +
      "pollution_level\030\003 \001(\005\022\017\n\007message\030\004 \001(\t\022-" +
      "\n\ttimestamp\030\005 \001(\0132\032.google.protobuf.Time" +
      "stamp\"]\n\013HVACCommand\022/\n\006action\030\001 \001(\0162\037.c" +
      "om.chuntao.HVACCommand.Action\"\035\n\006Action\022" +
      "\t\n\005START\020\000\022\010\n\004STOP\020\001\"_\n\014HVACResponse\022\020\n\010" +
      "location\030\001 \001(\t\022\016\n\006status\030\002 \001(\010\022-\n\ttimest" +
      "amp\030\003 \001(\0132\032.google.protobuf.Timestamp\"v\n" +
      "\rSensorMessage\022\020\n\010location\030\001 \001(\t\022\023\n\013air_" +
      "quality\030\002 \001(\t\022\017\n\007message\030\003 \001(\t\022-\n\ttimest" +
      "amp\030\004 \001(\0132\032.google.protobuf.Timestamp\"]\n" +
      "\013HVACMessage\022\016\n\006status\030\001 \001(\010\022\017\n\007message\030" +
      "\002 \001(\t\022-\n\ttimestamp\030\003 \001(\0132\032.google.protob" +
      "uf.Timestamp2\352\003\n\021SmartAirPollution\022J\n\rGe" +
      "tSensorData\022\032.com.chuntao.SensorRequest\032" +
      "\033.com.chuntao.SensorResponse\"\000\022R\n\021Analys" +
      "eSensorData\022\033.com.chuntao.SensorResponse" +
      "\032\034.com.chuntao.AnalyseResponse\"\000(\001\022I\n\013HV" +
      "ACControl\022\034.com.chuntao.AnalyseResponse\032" +
      "\030.com.chuntao.HVACCommand\"\000(\001\022G\n\nHVACSwi" +
      "tch\022\030.com.chuntao.HVACCommand\032\031.com.chun" +
      "tao.HVACResponse\"\000(\0010\001\022S\n\023SensorNotifica" +
      "tions\022\034.com.chuntao.AnalyseResponse\032\032.co" +
      "m.chuntao.SensorMessage\"\0000\001\022L\n\021HVACNotif" +
      "ications\022\031.com.chuntao.HVACResponse\032\030.co" +
      "m.chuntao.HVACMessage\"\0000\001B&\n\023com.chuntao" +
      ".serviceB\rSensorServiceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_chuntao_SensorRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chuntao_SensorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chuntao_SensorRequest_descriptor,
        new java.lang.String[] { "SensorId", });
    internal_static_com_chuntao_SensorResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_chuntao_SensorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chuntao_SensorResponse_descriptor,
        new java.lang.String[] { "Location", "PM25", "Temperature", "VOC", "Humidity", "CO", });
    internal_static_com_chuntao_AnalyseResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_chuntao_AnalyseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chuntao_AnalyseResponse_descriptor,
        new java.lang.String[] { "Analyse", "Location", "PollutionLevel", "Message", "Timestamp", });
    internal_static_com_chuntao_HVACCommand_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_chuntao_HVACCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chuntao_HVACCommand_descriptor,
        new java.lang.String[] { "Action", });
    internal_static_com_chuntao_HVACResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_chuntao_HVACResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chuntao_HVACResponse_descriptor,
        new java.lang.String[] { "Location", "Status", "Timestamp", });
    internal_static_com_chuntao_SensorMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_chuntao_SensorMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chuntao_SensorMessage_descriptor,
        new java.lang.String[] { "Location", "AirQuality", "Message", "Timestamp", });
    internal_static_com_chuntao_HVACMessage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_chuntao_HVACMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chuntao_HVACMessage_descriptor,
        new java.lang.String[] { "Status", "Message", "Timestamp", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
